name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build and push Docker image
      run: |
        docker build --pull -t ${{ secrets.DOCKER_USERNAME }}/ssh-client .
        docker push ${{ secrets.DOCKER_USERNAME }}/ssh-client
