name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      run: echo "${DOCKER_PAT}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Build and push Docker image
      run: |
        docker build --pull -t ${{ secrets.DOCKER_USERNAME }}/ssh-client .
        docker push ${{ secrets.DOCKER_USERNAME }}/ssh-client
